### ISSUE TITLE
`Personal access tokens with fine grained access do not support the GraphQL API`

### ISSUE THREAD

**Issue by aaronArinder** [actions/add-to-project#289]
with a PAT that has both `repo` and `project` scopes, I'm getting the following when trying to use the action:

```
Personal access tokens with fine grained access do not support the GraphQL API
```

Let me know if there's any troubleshooting I can do on my end; also, I'm wondering if this is a known issue?

**Comment by blampe** [comment]
FWIW this was fixed in https://github.com/github/roadmap/issues/622, the docs should probably be updated.

**Comment by SimenB** [comment]
What permissions are needed for the fine grained token?

**Comment by jdanyow** [comment]
Fine grained tokens work provided the token has the following:

- Repositories
  - Issues: Read
  - Metadata: Read
- Organization
  - Projects: Read and Write

![CleanShot 2023-12-04 at 15 04 36@2x](https://github.com/actions/add-to-project/assets/1306747/60cf9048-0742-4971-89e1-267e48853b89)

**Comment by keikoro** [comment]
> Fine grained tokens work

You forgot about the non-negligible caveat that so far, project permissions are _only_ available to organization accounts.

There is no such option when the "resource owner" of a fine-grained token is a regular user.

**Comment by jdanyow** [comment]
Correct 👍 -  I'm using this action with fine-grained tokens as described in https://github.com/actions/add-to-project/issues/289#issuecomment-1839684489 with a GitHub organization.
